#!/usr/bin/env node

// Doc: https://betterprogramming.pub/create-your-own-changelog-generator-with-git-aefda291ea93

const child = require("child_process");
const fs = require("fs");

if (!fs.existsSync("./CHANGELOG.md")) {
    fs.writeFileSync("./CHANGELOG.md", "", {flag: "w"});
}
let defaultVersion = "latest";
if (fs.existsSync("./package.json")) {
    const {version} = require(process.cwd() + "/package.json");
    defaultVersion = version || defaultVersion;
}

if (fs.existsSync("./composer.json")) {
    const {version} = require(process.cwd() + "/composer.json");
    defaultVersion = version || defaultVersion;
}

const args = process.argv.slice(2);
const notime = args.find(e => e === "--notime");
const amend = args.find(e => e === "--amend");

const gitTags = child.execSync(`git tag`).toString();
let lastTag = child.execSync(`git rev-list --max-parents=0 HEAD | tail -1`).toString().trim();
let tags = gitTags.split("\n");
if (!tags || tags.length === 0 || tags[0] === "") {
    tags = ["HEAD"];
}else{
    tags.push('HEAD');
}

let changelogData = [];
tags.forEach(tag => {
    if (tag === "") return;
    const output = child
        .execSync(`git log --format=%cs%n%B%H----DELIMITER---- ${tag}...${lastTag}`)
        .toString("utf-8");

    const commitsArray = output
        .split("----DELIMITER----\n")
        .map(commit => {
            const [date, message, sha] = commit.split("\n");
            return {sha, message, date};
        })
        .filter(commit => Boolean(commit.sha));

    const version = tag != "HEAD" ? tag : defaultVersion;
    console.log(`\x1b[36mVersion: ${version}\x1b[0m`);
    let newChangelog = `### Version: ${version}\n\n`;

    const features = [];
    const tasks = [];
    const fixes = [];
    const chores = [];

    commitsArray.forEach(commit => {
        if (appendCommit("fix[:]? ", commit, fixes)) return;
        if (appendCommit("feat[:]? ", commit, features)) return;
        if (appendCommit("add[:]? ", commit, features)) return;
        if (appendCommit("task[:]? ", commit, tasks)) return;
        if (appendCommit("chore[:]? ", commit, chores)) return;

    });
    newChangelog += renderList(`#### 📢 Features`,features);
    newChangelog += renderList(`#### 📋 Tasks`,tasks);
    newChangelog += renderList(`#### 👷 Fixes`,fixes);
    newChangelog += renderList(`#### 🧮 Chores`,chores);

    changelogData.push(newChangelog);
    lastTag = tag;
});

fs.writeFileSync("./CHANGELOG.md", `## Changelog\n\n${changelogData.reverse().join("")}`);
if(amend){
    child.execSync('git add --all && git commit --amend --no-edit')
    console.log('Amend commit message');
}
console.log('PROCESS FINISHED');

function appendCommit(tipo, commit, arreglo) {
    const pattern = new RegExp(tipo);
    if (pattern.test(commit.message)) {
        const shortHash = commit.sha.substring(0, 6);
        const date = notime ? "" : `**${commit.date}:**`;
        const message = commit.message.replace(new RegExp("^" + tipo, "g"), "");
        arreglo.push(`* ${date} ${message} (${shortHash})\n`);
        return true;
    }
    return false;
}

function renderList(title,arreglo){
    let newChangelog = '';
    if (arreglo.length) {
        newChangelog += `${title}\n`;
        arreglo.forEach(feature => {
            newChangelog += feature;
        });
        newChangelog += "\n";
        console.log(title.replace(/#+\s.*\s/g,'') +': '+ arreglo.length);
    }
    return newChangelog;
}

